name: CI

on:
  push:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'
      - '.github/workflows/ci.yml'

jobs:
  syntax_tests:
    name: Syntax Tests (${{ matrix.build }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: latest   # latest dev build
          - build: stable   # latest stable build
          - build: '3210'   # latest known ST3 build with a test binary
    steps:
      - uses: actions/checkout@v4
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          package_name: Spintax
